let cezalar = [
    {isim : "Kamu Alanlarına İzinsiz Giriş", para : 750, hapis :0, kamu :5, illegal : false, active : false, tceza : 0 },
    {isim : "Kamu Huzurunu Bozma", para : 250, hapis :10, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Alkollü Araç Kullanmak", para : 1000, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Geçiş Üstünlüğü Olan Araca Yol Vermemek", para : 100, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Hasarlı Araç Kullanmak", para : 500, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Kontrolsüz Sürüş", para : 500, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "3.Derece Hız Aşımı", para : 150, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "2.Derece Hız Aşımı", para : 300, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "1.Derece Hız Aşımı", para : 500, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Ehliyetsiz Araç Sürme", para : 1500, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasa Dışı U Dönüşü", para : 250, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Hatalı Sollama", para : 300, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Şerit Dışında Sürüş", para : 250, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasa Dışı Dönüş", para : 300, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Failure to Stop", para : 1000, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasa Dışı Park", para : 300, hapis : 0, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Vur-Kaç", para : 250, hapis : 4, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasa Dışı Yarış", para : 4000, hapis : 25, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasa Dışı Sürüş", para : 1000, hapis : 0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Gasp", para : 1000, hapis :15, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Araç Çalma Girişimi", para : 1000, hapis :0, kamu :15, illegal : false, active : false, tceza : 0 },
    {isim : "Çevreyi Rahatsız Etme", para : 2000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Darp", para : 2000, hapis :40, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "İzinsiz Görüntü Ve Ses Kaydı", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Maske-Zırh-Silah Kılıfı Bulundurma", para : 2500, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Plakasız Araç Kullanma", para : 1500, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "İllegal Modifiye", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Asılsız İhbar", para : 200, hapis :15, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Çalışanını Kandırma", para : 300, hapis :30, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "İllegal Madde Bulundurma", para : 1000, hapis :30, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kesici,Delici Alet Bulundurmak", para : 1000, hapis :10, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Siber Suçlar", para : 2500, hapis :10, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "İllegal Bölgede Bulunma", para : 2500, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Dolandırıcılık", para : 5000, hapis :20, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Dur İhtarına Uymamak", para : 1000, hapis :10, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Çalıntı Araç Kullanma", para : 2500, hapis :25, kamu :0, illegal : false, active : false, tceza : 5 },
    {isim : "Kırmızı Işıkta Geçme", para : 300, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Magandalık", para : 2000, hapis :20, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Sivil Yaralama Girişimi", para : 5000, hapis :65, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Adam Soymak", para : 3000, hapis :55, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Tehdit", para : 3000, hapis :20, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Sorgu Düzenine Uymama", para : 3000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kumar Oynatmak", para : 8000, hapis :40, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kesici,Delici Alet Ticareti", para : 10000, hapis :70, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Polise Direnme+Zorluk Çıkartmak", para : 2000, hapis :20, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Malına Zarar Vermek", para : 5000, hapis :10, kamu :0, illegal : false, active : false, tceza : 3 },
    {isim : "Şantaj", para : 5000, hapis :15, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Market Soygunu", para : 8000, hapis :30, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Adam Kaçırma", para : 6000, hapis :90, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasadışı Ticaret", para : 6000, hapis :80, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Tefecilik", para : 9000, hapis :60, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Ruhsatsız Silah Bulundurma", para : 7000, hapis :0, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Kesici,Delici Alet İle Adam Yaralama", para : 4000, hapis :100, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Devlet Çalışanını Yaralama", para : 5000, hapis :120, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Yalancı Şahitlik", para : 5000, hapis :40, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Haraç Kesme", para : 10000, hapis :30, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Ateşli Silah Ticareti", para : 20000, hapis :130, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Tutuklama Durumundan Kaçmak", para : 5000, hapis :40, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kuyumcu Soygunu", para : 20000, hapis :130, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Ateşli Silah İle Cinayet Girişimi", para : 15000, hapis :100, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Aracını Çalma Girişimi", para : 15000, hapis :30, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Banka/Merkez Banka Soygunu", para : 20000, hapis :180, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Memuru veya Barış Görevlisi Cinayeti", para : 0, hapis :99999999, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Memuru veya Barış Görevlisine Cinayet Girişimi", para : 0, hapis :200, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "İşkence", para : 30000, hapis :270, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "1.Derece Cinayet", para : 0, hapis :280, kamu :0, illegal : false, active : false, tceza : 0 },    
    {isim : "1.Derece Cinayet Girişimi", para : 0, hapis :140, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Esrar Bulundurmak", para : 2000, hapis : 20, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasal Sınır Üzerinde Esrar Tohumu/Bitkisi Bulundurmak", para : 4000, hapis : 30, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Kokain Bulundurmak", para : 1600, hapis : 0, kamu : 20, illegal : false, active : false, tceza : 0 },
    {isim : "Kokain Üretimi", para : 10000, hapis : 90, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Meth Bulundurmak", para : 2000, hapis : 25, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Meth Üretimi", para : 20000, hapis : 110, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Yasa Dışı İlaç Satışı", para : 12000, hapis : 80, kamu : 0, illegal : false, active : false, tceza : 0 },
    {isim : "Uyuşturucu Ticareti", para : 8000, hapis : 70, kamu : 0, illegal : false, active : false, tceza : 0 },



    // {isim : "Ağır Suçlar Çeteleşme", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    // {isim : "Ağır Suçlar Örgütlenmek", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Yasadışı Oluşum", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Kanuna Karşı Hareketlenme", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Terör Saldırısı", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Terör Saldırsı Girişimi", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Suikast", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Suikast Girişimi", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Organize Suç Örgütü Kuran", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
]
